# Generated by Django 4.2.5 on 2023-10-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orderitem_count_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productsize'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
    ]
